import type { ElementRecord, RecipeResult } from "@/lib/types";
import { buildFlavorText } from "@/lib/flavor-text";

type RecipeTuple = [string, string, string, string];

export const STARTING_ELEMENTS: ElementRecord[] = [
  { element: "Earth", emoji: "🌍", flavorText: buildFlavorText("Earth"), discoveredAt: 0, isStarter: true },
  { element: "Air", emoji: "💨", flavorText: buildFlavorText("Air"), discoveredAt: 1, isStarter: true },
  { element: "Water", emoji: "💧", flavorText: buildFlavorText("Water"), discoveredAt: 2, isStarter: true },
  { element: "Fire", emoji: "🔥", flavorText: buildFlavorText("Fire"), discoveredAt: 3, isStarter: true }
];

const RECIPES: RecipeTuple[] = [
  ["Air", "Air", "🌬️", "Wind"],
  ["Air", "Earth", "🟫", "Dust"],
  ["Air", "Fire", "💨", "Smoke"],
  ["Air", "Water", "🌫️", "Mist"],
  ["Earth", "Earth", "⛰️", "Mountain"],
  ["Earth", "Fire", "🌋", "Lava"],
  ["Earth", "Water", "🪹", "Mud"],
  ["Fire", "Fire", "☀️", "Sun"],
  ["Fire", "Water", "♨️", "Steam"],
  ["Water", "Water", "🌊", "Ocean"],
  ["Dust", "Earth", "🏜️", "Desert"],
  ["Dust", "Fire", "💥", "Ash"],
  ["Dust", "Water", "🧱", "Clay"],
  ["Wind", "Fire", "🌪️", "Wildfire"],
  ["Wind", "Water", "🌧️", "Rain"],
  ["Wind", "Earth", "🌪️", "Sandstorm"],
  ["Smoke", "Water", "☁️", "Cloud"],
  ["Smoke", "Earth", "🪨", "Soot"],
  ["Mist", "Earth", "🪴", "Plant"],
  ["Mist", "Fire", "🌈", "Rainbow"],
  ["Mountain", "Fire", "🌋", "Volcano"],
  ["Mountain", "Water", "🏞️", "River"],
  ["Mountain", "Wind", "🦅", "Eagle"],
  ["Mountain", "Stone", "🗜️", "Pressure"],
  ["Lava", "Water", "🪨", "Stone"],
  ["Lava", "Air", "🪟", "Glass"],
  ["Mud", "Fire", "🧱", "Brick"],
  ["Mud", "Plant", "🌾", "Swamp"],
  ["Sun", "Water", "🧂", "Salt"],
  ["Sun", "Plant", "🌻", "Flower"],
  ["Sun", "Earth", "🕰️", "Time"],
  ["Steam", "Air", "☁️", "Cloud"],
  ["Steam", "Earth", "💨", "Geyser"],
  ["Ocean", "Earth", "🏝️", "Island"],
  ["Ocean", "Wind", "🌊", "Wave"],
  ["Rain", "Earth", "🌱", "Seed"],
  ["Rain", "Plant", "🌳", "Tree"],
  ["Cloud", "Fire", "⚡", "Lightning"],
  ["Cloud", "Earth", "⛈️", "Storm"],
  ["Plant", "Earth", "🌿", "Grass"],
  ["Plant", "Water", "🌊", "Algae"],
  ["Plant", "Fire", "🌫️", "Incense"],
  ["Plant", "Wind", "🍃", "Leaf"],
  ["Stone", "Stone", "🪨", "Boulder"],
  ["Stone", "Water", "💎", "Gem"],
  ["Stone", "Wind", "🗿", "Statue"],
  ["Brick", "Brick", "🏠", "House"],
  ["Brick", "Fire", "🏭", "Kiln"],
  ["Brick", "Water", "🛁", "Bath"],
  ["Swamp", "Energy", "🐸", "Life"],
  ["Salt", "Ocean", "🐟", "Fish"],
  ["Salt", "Plant", "🍟", "Snack"],
  ["Flower", "Wind", "🌼", "Pollen"],
  ["Flower", "Water", "🪷", "Lotus"],
  ["Flower", "Fire", "🌶️", "Spice"],
  ["Time", "Plant", "🌲", "Forest"],
  ["Time", "Stone", "🦴", "Fossil"],
  ["Time", "Water", "🧊", "Ice"],
  ["Geyser", "Stone", "♨️", "Hot Spring"],
  ["Island", "Fire", "🌴", "Palm"],
  ["Island", "Tree", "🥥", "Coconut"],
  ["Wave", "Stone", "🏖️", "Beach"],
  ["Seed", "Earth", "🌱", "Sprout"],
  ["Seed", "Time", "🌽", "Crop"],
  ["Tree", "Fire", "🪵", "Wood"],
  ["Tree", "Tool", "🪓", "Lumber"],
  ["Tree", "Water", "🍎", "Fruit"],
  ["Air", "Human", "🔊", "Sound"],
  ["Lightning", "Earth", "⚡", "Energy"],
  ["Lightning", "Metal", "🤖", "Robot"],
  ["Storm", "Ocean", "🌀", "Hurricane"],
  ["Grass", "Earth", "🌾", "Field"],
  ["Grass", "Fire", "🔥", "Ember"],
  ["Algae", "Sun", "🪸", "Coral"],
  ["Leaf", "Water", "🍵", "Tea"],
  ["Boulder", "Hill", "🏔️", "Peak"],
  ["Boulder", "Fire", "🛡️", "Metal"],
  ["Gem", "Fire", "💍", "Jewelry"],
  ["Statue", "Life", "🗽", "Monument"],
  ["House", "House", "🏘️", "Village"],
  ["House", "Stone", "🏰", "Castle"],
  ["Kiln", "Clay", "🏺", "Pottery"],
  ["Bath", "House", "🛀", "Bathroom"],
  ["Life", "Earth", "🦠", "Bacteria"],
  ["Life", "Ocean", "🐋", "Whale"],
  ["Life", "Plant", "🧬", "DNA"],
  ["Fish", "Time", "🐊", "Lizard"],
  ["Pollen", "Life", "🐝", "Bee"],
  ["Lotus", "Mud", "🪷", "Bloom"],
  ["Spice", "Plant", "🌿", "Herb"],
  ["Forest", "Mist", "🧚", "Fairy"],
  ["Forest", "Tree", "🦌", "Deer"],
  ["Ice", "Air", "❄️", "Snow"],
  ["Ice", "Fire", "💧", "Melt"],
  ["Hot Spring", "Earth", "♨️", "Spa"],
  ["Palm", "Beach", "🏖️", "Paradise"],
  ["Coconut", "Tool", "🥥", "Bowl"],
  ["Beach", "Sun", "🕶️", "Vacation"],
  ["Sprout", "Time", "🌿", "Herb"],
  ["Crop", "House", "🏡", "Farm"],
  ["Wood", "Tool", "🛠️", "Tool"],
  ["Wood", "Fire", "🔥", "Charcoal"],
  ["Fruit", "Time", "🍷", "Wine"],
  ["Fruit", "Water", "🧃", "Juice"],
  ["Energy", "Mud", "👤", "Human"],
  ["Energy", "Stone", "⚙️", "Machine"],
  ["Energy", "Cloud", "🌩️", "Thunder"],
  ["Hurricane", "House", "🧹", "Debris"],
  ["Field", "House", "🏘️", "Town"],
  ["Ember", "Stone", "⚒️", "Forge"],
  ["Coral", "Ocean", "🐠", "Reef"],
  ["Tea", "Fire", "🍵", "Kettle"],
  ["Peak", "Wind", "🪁", "Glider"],
  ["Metal", "Water", "🚢", "Boat"],
  ["Metal", "Fire", "⚔️", "Blade"],
  ["Metal", "Tool", "🔩", "Gear"],
  ["Jewelry", "Human", "👑", "Crown"],
  ["Village", "Village", "🏙️", "City"],
  ["Castle", "Human", "🤴", "Kingdom"],
  ["Pottery", "Plant", "🪴", "Planter"],
  ["Bacteria", "Water", "🦠", "Plague"],
  ["Whale", "Human", "🐳", "Legend"],
  ["DNA", "Energy", "🧪", "Mutation"],
  ["Lizard", "Time", "🦖", "Dinosaur"],
  ["Bee", "Flower", "🍯", "Honey"],
  ["Fairy", "Energy", "✨", "Magic"],
  ["Deer", "Human", "🏹", "Hunt"],
  ["Snow", "Wind", "🌨️", "Blizzard"],
  ["Snow", "Mountain", "⛷️", "Ski"],
  ["Spa", "Human", "🧖", "Relaxation"],
  ["Paradise", "Human", "🏝️", "Resort"],
  ["Vacation", "Time", "📸", "Memory"],
  ["Farm", "Human", "🚜", "Farmer"],
  ["Tool", "Stone", "⛏️", "Pickaxe"],
  ["Tool", "Metal", "🔨", "Hammer"],
  ["Charcoal", "Pressure", "💎", "Diamond"],
  ["Wine", "Time", "🍾", "Celebration"],
  ["Juice", "Ice", "🥤", "Smoothie"],
  ["Human", "Stone", "🗿", "Sculptor"],
  ["Human", "Metal", "🛡️", "Armor"],
  ["Human", "Tree", "🏹", "Archer"],
  ["Human", "House", "👨‍👩‍👧‍👦", "Family"],
  ["Machine", "Human", "🚗", "Car"],
  ["Machine", "Time", "⏰", "Clock"],
  ["Thunder", "Rain", "⛈️", "Tempest"],
  ["Town", "Town", "🌆", "Metropolis"],
  ["Forge", "Blade", "🗡️", "Sword"],
  ["Forge", "Armor", "🛡️", "Shield"],
  ["Reef", "Life", "🐠", "Aquarium"],
  ["Boat", "Ocean", "⛵", "Sailboat"],
  ["Blade", "Human", "🗡️", "Warrior"],
  ["Gear", "Machine", "🏭", "Factory"],
  ["City", "Human", "🏛️", "Civilization"],
  ["City", "Energy", "💡", "Electricity"],
  ["Kingdom", "Castle", "👑", "Empire"],
  ["Planter", "Flower", "🪴", "Garden"],
  ["Mutation", "Life", "🧟", "Monster"],
  ["Dinosaur", "Time", "🦴", "Extinction"],
  ["Honey", "Bread", "🍯", "Toast"],
  ["Magic", "Human", "🧙", "Wizard"],
  ["Magic", "Stone", "🔮", "Crystal Ball"],
  ["Blizzard", "Mountain", "🏔️", "Avalanche"],
  ["Memory", "Human", "📖", "Story"],
  ["Farmer", "Field", "🌾", "Harvest"],
  ["Pickaxe", "Mountain", "⛏️", "Mine"],
  ["Hammer", "Metal", "🔧", "Anvil"],
  ["Pressure", "Earth", "🕳️", "Cave"],
  ["Pressure", "Plant", "⛽", "Oil"],
  ["Diamond", "Human", "💍", "Ring"],
  ["Celebration", "Fire", "🎆", "Fireworks"],
  ["Smoothie", "Fruit", "🍹", "Cocktail"],
  ["Armor", "Warrior", "🛡️", "Knight"],
  ["Family", "House", "🏡", "Home"],
  ["Car", "Energy", "🚙", "Engine"],
  ["Clock", "Energy", "⏱️", "Timer"],
  ["Tempest", "Ocean", "🌊", "Tsunami"],
  ["Metropolis", "Electricity", "🌃", "Neon"],
  ["Sword", "Knight", "⚔️", "Battle"],
  ["Shield", "Knight", "🛡️", "Guardian"],
  ["Factory", "Energy", "🏭", "Industry"],
  ["Civilization", "Story", "📚", "History"],
  ["Electricity", "Metal", "💻", "Computer"],
  ["Empire", "Time", "🏛️", "Ruins"],
  ["Garden", "Life", "🦋", "Butterfly"],
  ["Monster", "Human", "😱", "Fear"],
  ["Wizard", "Fire", "🐉", "Dragon"],
  ["Wizard", "Story", "📜", "Spellbook"],
  ["Crystal Ball", "Time", "🔮", "Prophecy"],
  ["Avalanche", "Village", "🏚️", "Disaster"],
  ["Harvest", "Fire", "🍞", "Bread"],
  ["Mine", "Tool", "💣", "Dynamite"],
  ["Anvil", "Metal", "⚓", "Anchor"],
  ["Cave", "Life", "🦇", "Bat"],
  ["Oil", "Fire", "🛢️", "Fuel"],
  ["Ring", "Fire", "💍", "Artifact"],
  ["Fireworks", "City", "🎇", "Festival"],
  ["Cocktail", "Vacation", "🍸", "Party"],
  ["Knight", "Dragon", "🏰", "Quest"],
  ["Home", "Garden", "🏡", "Estate"],
  ["Engine", "Metal", "🚂", "Train"],
  ["Timer", "Bomb", "💣", "Countdown"],
  ["Tsunami", "City", "🌊", "Flood"],
  ["Neon", "City", "🕹️", "Arcade"],
  ["Battle", "History", "🏺", "Myth"],
  ["Guardian", "Magic", "🗿", "Golem"],
  ["Industry", "Oil", "🏭", "Refinery"],
  ["History", "Human", "🏺", "Museum"],
  ["Computer", "Electricity", "🌐", "Internet"],
  ["Ruins", "Forest", "🗺️", "Temple"],
  ["Butterfly", "Flower", "🌺", "Spring"],
  ["Fear", "Night", "👻", "Ghost"],
  ["Dragon", "Mountain", "🐉", "Dragon Lair"],
  ["Spellbook", "Wizard", "📚", "Library"],
  ["Prophecy", "Human", "🧭", "Destiny"],
  ["Disaster", "Human", "🚨", "Emergency"],
  ["Bread", "Fire", "🍞", "Toast"],
  ["Dynamite", "Mountain", "💥", "Tunnel"],
  ["Anchor", "Boat", "⚓", "Harbor"],
  ["Bat", "Cave", "🦇", "Echo"],
  ["Fuel", "Engine", "🚀", "Rocket"],
  ["Artifact", "Museum", "🏺", "Relic"],
  ["Festival", "Music", "🎉", "Concert"],
  ["Party", "Music", "💃", "Dance"],
  ["Quest", "Story", "🗺️", "Adventure"],
  ["Train", "City", "🚉", "Station"],
  ["Flood", "Earth", "🌾", "Delta"],
  ["Arcade", "Computer", "👾", "Game"],
  ["Golem", "Life", "🧱", "Guardian Life"],
  ["Internet", "Human", "📱", "Social Media"],
  ["Temple", "Time", "🗿", "Ancient"],
  ["Spring", "Rain", "🌸", "Blossom"],
  ["Ghost", "Story", "🏚️", "Haunting"],
  ["Destiny", "Quest", "⭐", "Hero"],
  ["Emergency", "Energy", "🚁", "Rescue"],
  ["Tunnel", "Train", "🚇", "Subway"],
  ["Harbor", "City", "⚓", "Port"],
  ["Rocket", "Fire", "🌌", "Space"],
  ["Relic", "Magic", "🗝️", "Treasure"],
  ["Adventure", "Hero", "🏆", "Victory"],
  ["Station", "Electricity", "🚄", "Transit"],
  ["Game", "Human", "🎮", "Player"],
  ["Social Media", "Human", "📣", "Viral"],
  ["Hero", "Dragon", "🏆", "Champion"],
  ["Rescue", "Mountain", "🚁", "Helicopter"],
  ["Space", "Human", "👨‍🚀", "Astronaut"],
  ["Treasure", "Island", "💰", "Pirate"],
  ["Player", "Game", "🏅", "High Score"],
  ["Astronaut", "Space", "🛰️", "Satellite"],
  ["Pirate", "Boat", "🏴‍☠️", "Shipwreck"],
  ["Satellite", "Internet", "📡", "Signal"],
  ["Signal", "Human", "📻", "Radio"],
  ["Music", "Human", "🎵", "Song"],
  ["Song", "Electricity", "🎧", "Synth"],
  ["Night", "Sky", "🌙", "Moon"],
  ["Air", "Cloud", "☁️", "Sky"],
  ["Time", "Sky", "🌌", "Night"],
  ["Sound", "Human", "🎵", "Music"],
  ["Moon", "Ocean", "🦀", "Tide"],
  ["Tide", "Beach", "🐚", "Shell"],
  ["Shell", "Life", "🐢", "Turtle"],
  ["Pressure", "Stone", "🪨", "Ore"],
  ["Ore", "Fire", "🔩", "Steel"],
  ["Dynamite", "Fire", "💣", "Bomb"],
  ["Steel", "Engine", "🚂", "Locomotive"],
  ["Bread", "Human", "🥪", "Meal"],
  ["Meal", "Fire", "🍳", "Cooking"],
  ["Cooking", "Spice", "🍛", "Curry"],
  ["Human", "Music", "🎤", "Singer"],
  ["Singer", "Festival", "🎙️", "Performance"]
];

export function normalizeElementName(value: string) {
  return value.trim().replace(/\s+/g, " ");
}

export function createPairKey(first: string, second: string) {
  return [normalizeElementName(first), normalizeElementName(second)]
    .sort((left, right) => left.localeCompare(right))
    .join("::");
}

export const PREDEFINED_RECIPES = new Map<string, RecipeResult>(
  RECIPES.map(([first, second, emoji, element]) => [
    createPairKey(first, second),
    {
      element,
      emoji,
      flavorText: buildFlavorText(element),
      source: "predefined" as const
    }
  ])
);

export function getPredefinedResult(first: string, second: string) {
  return PREDEFINED_RECIPES.get(createPairKey(first, second));
}

export const ALL_PREDEFINED_ELEMENTS = Array.from(
  new Map(
    [
      ...STARTING_ELEMENTS.map((entry) => [entry.element, entry]),
      ...RECIPES.map(([, , emoji, element], index) => [
        element,
        { element, emoji, flavorText: buildFlavorText(element), discoveredAt: index + 10 }
      ])
    ].map(([key, value]) => [key, value as ElementRecord])
  ).values()
);
